export const RTUS_ADD_TO_UPLOAD_QUEUE = 'RTUS_ADD_TO_UPLOAD_QUEUE';
export const RTUS_ADD_TO_UPLOAD_QUEUE_FAILED = 'RTUS_ADD_TO_UPLOAD_QUEUE_FAILED';
export const RTUS_COMMIT_TO_UPLOAD_QUEUE = 'RTUS_COMMIT_TO_UPLOAD_QUEUE';

export const RTUS_UPLOAD_ALL = 'RTUS_UPLOAD_ALL';
export const RTUS_UPLOAD_ALL_FAILED = 'RTUS_UPLOAD_ALL_FAILED';
export const RTUS_UPLOAD_START = 'RTUS_UPLOAD_START';
export const RTUS_UPLOAD_FINISHED = 'RTUS_UPLOAD_FINISHED';
export const RTUS_UPLOAD_PROGRESS = 'RTUS_UPLOAD_PROGRESS';
export const RTUS_UPLOAD_FAILED = 'RTUS_UPLOAD_FAILED';

export const RTUS_REMOVE_ALL_FILES = 'RTUS_REMOVE_ALL_FILES';
export const RTUS_REMOVE_FILE = 'RTUS_REMOVE_FILE';
